# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
env:
  Number_one: github.event.inputs.first_num
  Number_two: github.event.inputs.second_num
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      first_num:
        description: 'first_num'
        required: true
      second_num:
        description: 'second_num'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        # run: 
        #   python pyprime.py
        # uses: actions/checkout@v3
        # with:
        #   first_num: ${{ inputs.first_num }}
        #   second_num: ${{ inputs.second_num }}
        #   path: ./pyprime.py
        run:
          python pyprime.py ${Number_one} ${Number_two}

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
